name: Tests CI

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

on: 
  pull_request:
    branches:
      - master
      - release/*
      - feature/*
jobs:
  build:

    name: Jest
    runs-on: ubuntu-20.04 # using higher versions of ubuntu will cause an issue with MongoDB

    strategy:
      matrix:
        node-version: [16.x]

    steps:

      # Log Environment Variables
      - name: Log Environment Variables
        run: |
          echo "COVERAGE_STATEMENTS=${{ vars.COVERAGE_STATEMENTS }}"
          echo "COVERAGE_BRANCHES=${{ vars.COVERAGE_BRANCHES }}"
          echo "COVERAGE_FUNCTIONS=${{ vars.COVERAGE_FUNCTIONS }}"
          echo "COVERAGE_LINES=${{ vars.COVERAGE_LINES }}"
